services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        user: "1000"
        container_name: commande_php
        env_file:
            - ./.env.prod
        volumes:
            - .:/var/www/symfony
            - /var/www/symfony/vendor
        networks:
            - symfony-network

    nginx:
        image: nginx:stable
        container_name: commande_nginx
        env_file:
            - ./.env.prod
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/symfony
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - symfony-network

    db:
        image: mariadb:latest
        container_name: commande_db
        env_file:
            - ./.env.prod
        ports:
            - "3306:3306"
        volumes:
            - /home/matt/Dev/projects/maalsi_cubes_3/prod/mysql_commande:/var/lib/mysql
        networks:
            - symfony-network

    rabbitmq:
         image: rabbitmq:3-management
         container_name: rabbitmq
         env_file:
             - ./.env.prod
         ports:
             - "5672:5672"
             - "15672:15672"
         networks:
             - symfony-network

networks:
    symfony-network:
        driver: bridge
